### ISSUE TITLE
Improve the register page

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#10]
Currenty, in the register page there's only option to add username, email, password. The final register page should ask user to enter the follwing details:
1. Name
2.Email id
3. Country
4. Profession(Student/Developer/Others)
5. Password(Check that the password should contain 8 characters including a special case character)
6. Confirm Password

It's not necessary that you need to take this whole task. You can take the task of developing the frontend, or if the frontend is created by someone you can collaborate with him to add backend functionality. If you are comfortable in creating both you can take both. Please mention in comments which type of task you are going to take.

**Comment by deepak2431** [comment]
![Screenshot from 2019-12-05 14-34-21](https://user-images.githubusercontent.com/44617923/70220322-66fd3b00-176c-11ea-9b24-152568531e66.png)

Design you can choose to create this page. Let me know in comments before taking up the issue what sort of Ui would you be designing.

**Comment by nikunjagarwal321** [comment]
Can the user register in 2 different pages? For eg: on the first page he'll enter the username,email, password and then he'll be redirected to a page where he has to enter the other details i.e. Country, Profession and Image?

**Comment by moraxella** [comment]
I want to work on this issue, ontly the frotend part for now. Kindly can you suggest me something related to UI, because i haven't done anything regarding this in the past.

**Comment by deepak2431** [comment]
@moraxella Sure, have a go. You can check out dribble or theme forest and pickup any template from there. Let me know once which template you have picked up. You can for sure only to frontend I will create a new branch frontend for that purpose. Thanks :)

**Comment by nikunjagarwal321** [comment]
@deepak2431 Can I work on this issue. Also, will it be okay to implement the login by extending it to 2 separate pages. In the first page, the user will enter the username, email and password. And in the second page, he'll enter the other details such as country, profession etc.

**Comment by deepak2431** [comment]
@nikunjagarwal321 moraxella wants to work on the frontend of this issue. So, I think you should wait until he finishes the frontend. Only he has completed the frontend you can take it and implement all the backend functionality. I would request you to take other issues till that :)

**Comment by nikunjagarwal321** [comment]
@deepak2431 sure. @moraxella Do let me know after you have completed the frontend part so that I can start with the backend work.

**Comment by moraxella** [comment]
@nikunjagarwal321 yeah sure! I'll let you know

**Comment by moraxella** [comment]
![Screenshot from 2019-12-16 14-28-12](https://user-images.githubusercontent.com/45992427/70893185-99325680-2010-11ea-88b3-b0c88293ee9c.png)

Is this fine? Like something related to this.

**Comment by deepak2431** [comment]
@moraxella Yeah it's fine for me.

**Comment by deepak2431** [comment]
@moraxella Are you working on the frontend?

**Comment by moraxella** [comment]
Yes, I'm working on it, give me some time to complete it.
