### ISSUE TITLE
Improve the home page

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#13]
Expected changes to be done to improve the home page:
1. Improve the nav bar
2. Currently, the whole blog post is being displayed for each post. Make it so that only part of it should be displayed. After opening a specific blog post it should display the whole content.
3. Make all the blogs to be displayed in the form of grid.
4. Add footer
You can make other changes too to make it awesome. You can check some of the developer's blog website for reference.

**Comment by snehalkhandve** [comment]
@deepak2431 can I work on this issue ?

**Comment by deepak2431** [comment]
@snehalkhandve Sure, have a go!

**Comment by deepak2431** [comment]
@snehalkhandve Are you working on this issue?

**Comment by snehalkhandve** [comment]
@deepak2431 yes I am working on the issue . Will upload the screenshot of home page before generating pr.

**Comment by deepak2431** [comment]
@snehalkhandve Sure, thanks!

**Comment by snehalkhandve** [comment]
![Screenshot from 2019-12-13 21-53-07](https://user-images.githubusercontent.com/52536837/70815309-3f087a00-1df3-11ea-844e-8a06ecddfef4.png)
This is the screenshot of home page after the changes I have done.Can I generate the pull request now ?

**Comment by deepak2431** [comment]
@snehalkhandve The color used for the background looks cool to me. But I would suggest you to make the sidebar color consistent with the homepage. Also please make some editing to navbar according to you. Rest is fine for me. You can open a PR after that.

**Comment by snehalkhandve** [comment]
Yup changed the color for sidebar
