### ISSUE TITLE
Add features to show feedback to post 

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#15]
For each of the blog post written by the users add emojis so the reader can give feedback to the post.

**Comment by gaurav618618** [comment]
i am interested to work on this issue.

**Comment by deepak2431** [comment]
@gaurav618618 Sure, have a go.

**Comment by gaurav618618** [comment]
![comment](https://user-images.githubusercontent.com/29380890/70451032-b3c57680-1aca-11ea-9162-8bcfbf5e30f4.PNG)

**Comment by gaurav618618** [comment]
should i make any changes or is it looking good?

**Comment by deepak2431** [comment]
@gaurav618618 Great job. Only one suggestions the label of the comment is not properly aligned . Can you please fix that?
Thanks!

**Comment by gaurav618618** [comment]
![comment](https://user-images.githubusercontent.com/29380890/70456410-0d7e6e80-1ad4-11ea-90c7-7819f7d6fc3b.PNG)
Does it look better now?

**Comment by deepak2431** [comment]
@gaurav618618 Yeah, go ahead!

**Comment by deepak2431** [comment]
Resolved in #27
