### ISSUE TITLE
Add option to select topic

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#16]
While writing a blog post for now the users can only select title and write the post. Add features so that the users can choose the topic about which they are going to write the post.

**Comment by Kartik-Sama** [comment]
Hello Deepak! Do you expect to add buttons to create post forum? And place a topic column in db?

**Comment by deepak2431** [comment]
Yeah, that can be done for now. Good to display the topic as a tag on the post. You can join over the gitter channel for more discussion.
Thanks:)

**Comment by Kartik-Sama** [comment]
![sample](https://user-images.githubusercontent.com/44060484/70891486-51f69680-200d-11ea-9e5f-7efde526d48d.png)
Please checkout if a dropdown list like this is good to go with.

**Comment by deepak2431** [comment]
@Kartik-Sama It's good for me. Go ahead !

**Comment by deepak2431** [comment]
Resolved in #42
