### ISSUE TITLE
Add a search bar to the application

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#18]

**Comment by gaurav618618** [comment]
hey @deepak2431  can i work on this.

**Comment by deepak2431** [comment]
@gaurav618618 Sure

**Comment by gaurav618618** [comment]
![home](https://user-images.githubusercontent.com/29380890/71302589-d90f8a00-23d2-11ea-9dc1-857987e57fc3.PNG)

**Comment by deepak2431** [comment]
@gaurav618618 Looks good to me go ahead.

**Comment by deepak2431** [comment]
Resolved in #50
