### ISSUE TITLE
Improve the UI of the WebApp

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#3]
The current UI/UX of the web app doesn't looks good. Make it more attractive by suggesting some of the mockups for the UI/UX design of the Web App.
Add detailed description of the changes you are going to make. 
Refer #8 for getting a better idea of what this application is about.

**Comment by chtushar** [comment]
I would like to work on this issue.

**Comment by deepak2431** [comment]
@chtushar Sure, go ahead!
