### ISSUE TITLE
Add features to sort the post

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#31]
Currently, all the posts are displayed according to the date created. You can add a sidebar to sort the post by following way:
1. By tags
2. By most commented posts
3. Display all the posts between a particular date.
4. By most liked posts

**Comment by Raghwendra-Dey** [comment]
Can i take up this issue?
could you please guide, what to look for to tackle this?
Also is there any feature of liking at all, if not how could we sort according to that?

**Comment by deepak2431** [comment]
@Raghwendra-Dey Sure, you can work on this. You can check above for the available options to sort the post. You need to write different query for sorting the post through each options.

**Comment by Raghwendra-Dey** [comment]
But what do you mean when you say by most liked post? Is there any feature of liking the post?
On what basis would it be most liked post?

**Comment by deepak2431** [comment]
@Raghwendra-Dey There is no features of liking the post yet as @gaurav618618 is already working on it. For now you can implement it with other options. Better to start implementing it with title if you want.

**Comment by Raghwendra-Dey** [comment]
Okay, currently i am working in sorting posts between two dates, and the most commented one.
By title do you mean alphabetically arranging them by title?

**Comment by deepak2431** [comment]
@Raghwendra-Dey That's great go ahead! No by title I mean to get all the posts with same title.

**Comment by Raghwendra-Dey** [comment]
If i am not wrong, the search feature does the same thing no?

**Comment by deepak2431** [comment]
> If i am not wrong, the search feature does the same thing no?

Yeah, the search features does the same. Sorry I forgot about that. Don't add option to sort it by title. As like features has been implemented so you can try by that too.
