### ISSUE TITLE
Add option to add all possible tags while writing a post

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#40]
There should be option to select all possible tags after a topic is selected. The tags should be displayed at the last of post.

**Comment by rrohit2901** [comment]
CAN I WORK ON THIS ISSUE??

**Comment by deepak2431** [comment]
@rrohit2901 Sure, have a go!

**Comment by deepak2431** [comment]
@rrohit2901 Any updates about your work?

**Comment by rrohit2901** [comment]
I am working on it. Will complete it by today
