### ISSUE TITLE
Add features to ask question

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#41]
Currently, in the blog application only the users are able to write a post. There should be a option in nav bar to post any questions after registering. The other users should be able to answer the questions too.

**Comment by Kartik-Sama** [comment]
I am willing to work on this issue.

**Comment by deepak2431** [comment]
@Kartik-Sama Sure, go ahead!

**Comment by deepak2431** [comment]
Resolved in #52
