### ISSUE TITLE
Add features to save the post 

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#46]
Currently, other users can only view the post but couldn't save it to read it later. You should add a icon to save the post for later read and the saved post should be displayed on the other's users profile.

**Comment by rrohit2901** [comment]
what should be visible on other's user profile??

**Comment by deepak2431** [comment]
Better to include a nav tag after getting over it user can view all the save post. Make the saved post nav tag visible only after login. Thanks:)

**Comment by gaurav618618** [comment]
Hey @deepak2431  is this issue assigned?

**Comment by gaurav618618** [comment]
I would like to work on this issue.

**Comment by deepak2431** [comment]
Sure, go ahead!
