### ISSUE TITLE
Add features to record unique view of a post

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#54]

**Comment by Kartik-Sama** [comment]
What exactly is expected to be done in this @deepak2431 ?

**Comment by deepak2431** [comment]
@Kartik-Sama After opening a post by different users it should record the total number of unique users who have read the post.

**Comment by Kartik-Sama** [comment]
@deepak2431  by opening the post do you mean going to post detail view? If so I would like to take up this issue.

**Comment by deepak2431** [comment]
@Kartik-Sama Yeah going to the post detail View.
