### ISSUE TITLE
Add features to share the post

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#55]
Users should have a option to share the post on Linkdedln and other social sites.

**Comment by Kartik-Sama** [comment]
I would like to work on this issue.

**Comment by deepak2431** [comment]
@Kartik-Sama Sure, go ahead!

**Comment by Kartik-Sama** [comment]
Couple of clarifications... 
The linkedin sharable url isn't functioning currently. it shows some message saying it's their error. Couldn't find any alternative link.
And for the icons used where should we mention credits?

**Comment by Kartik-Sama** [comment]
![Screenshot from 2019-12-26 14-50-00](https://user-images.githubusercontent.com/44060484/71469433-2040b500-27ef-11ea-9f16-275534df93e5.png)
Currently facebook and twitter links work as expected.

**Comment by Kartik-Sama** [comment]
I have made a pull request. Please let me know if changes are required. Thanks =D.

**Comment by deepak2431** [comment]
Resolved in #57
