### ISSUE TITLE
Add new issue template

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#7]

**Comment by nimishgo** [comment]
@deepak2431 Can I work on this?

**Comment by deepak2431** [comment]
@nimishgo Sure, have a go.

**Comment by Sai-Adarsh** [comment]
@deepak2431 What's the status? Shall I work on this?

**Comment by deepak2431** [comment]
@Sai-Adarsh Until it's open you can work on this.

**Comment by deepak2431** [comment]
@nimishgo @Sai-Adarsh Are you working on this? As this issue won't require more than 1 days I think.
