### ISSUE TITLE
Suggest a name for this application

### ISSUE THREAD

**Issue by deepak2431** [deepak2431/djangoBlog#8]
As I am planning to host this application online as developer blogs. The functionality would include:
1. Users can register themselves and  create their own profile. Add option to register with github, twitter, linkedln.
2. Users can write a blog on any technical topics. They can also write a blog to create some of the cool stuffs as a  small website or anything else.
3. Users can read the blog, add comments, like the blog, add it as their favourite blog so that they can read it later too. 
4.Add functionality to let users share the blog on twitter, linkedln.

This is the brief functionality of the application. More ideas for the application are welcomed. Please feel free me to contact me if you have any ideas or want to contribute to this project to take it forward.
Email id - deepakdk2431@gmail.com

**Comment by GSri30** [comment]
Can I work on this?

**Comment by deepak2431** [comment]
@GSri30 Sure, you can. Sorry for replying late.

**Comment by GSri30** [comment]
Cool.
I just have a set of names which you can select from (if you like any):
ExpreSS
UtteR
RendeR
Tech-HerE
I hope you draw something useful out of it!

**Comment by deepak2431** [comment]
@GSri30 Tech-Here sounds good to me!

**Comment by GSri30** [comment]
Cool :)

**Comment by imagebind** [comment]
Thinklogic.com is a suggestion from my end :)
